# Generated by Django 4.2.3 on 2023-07-06 14:42

from django.db import migrations, models
import django.db.models.deletion
import malpractice_tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0007_session_alter_institutionuser_picture'),
        ('malpractice_tracking', '0002_delete_fillformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('registration_no', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/')),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('absolved', 'absolved'), ('accused', 'accused'), ('neutral', 'neutral')], max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.department')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionprofile')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionuser')),
                ('session', models.ForeignKey(default=malpractice_tracking.models.get_current_year, on_delete=django.db.models.deletion.SET_DEFAULT, to='institutions.session')),
            ],
        ),
    ]
