# Generated by Django 4.2.3 on 2023-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice_tracking', '0005_alter_fillformmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillformmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
