# Generated by Django 4.2.3 on 2023-07-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malpractice_tracking', '0007_alter_fillformmodel_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FillFormModel',
        ),
    ]
