# Generated by Django 4.2.3 on 2023-07-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import malpractice_tracking.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0007_session_alter_institutionuser_picture'),
        ('malpractice_tracking', '0008_delete_fillformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillFormModel',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='img/accused/')),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('absolved', 'absolved'), ('accused', 'accused'), ('neutral', 'neutral')], max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.department')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionprofile')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(default=malpractice_tracking.models.get_current_year, on_delete=django.db.models.deletion.SET_DEFAULT, to='institutions.session')),
            ],
            options={
                'verbose_name_plural': 'Fill Form',
            },
        ),
    ]
