# Generated by Django 4.2.3 on 2023-07-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_institution_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institution_id',
        ),
    ]
