# Generated by Django 4.2.3 on 2023-07-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_department_alter_institutionprofile_institution_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionprofile',
            old_name='user_id',
            new_name='admin_id',
        ),
    ]
