# Generated by Django 4.2.3 on 2023-07-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_session_alter_institutionuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionuser',
            name='picture',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='img/profile_pic'),
        ),
    ]
